config/routes.rb
Rails.application.routes.draw do
  resources :adminloans
  resources :loans
  resources :packages
  get 'userorder', to: 'loans#userorder'

  resources :deposits
  resources :feedbacks
  resources :features
  resources :boards
  resources :headers
  resources :cards
  resources :bills
  resources :transfers do
    resources :otps
  end
  resources :transactions
  resources :contacts
  resources :accounts
  resources :banners
  resources :blogs
  resources :faqs
  resources :plans
  resources :sections
  resources :services
  resources :abouts
  # mount Ckeditor::Engine => '/ckeditor'
  resources :welcomes
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end
    root "welcomes#index"

      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :abtimg, AbtimgUploader

end

app/models/account.rb
class Account < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :account_number, use: :slugged
  belongs_to :user
  
  validates :balance, presence: true
  before_validation :load_defaults
  has_many :transfers, dependent: :destroy
  accepts_nested_attributes_for :transfers

  def load_defaults
    if self.new_record?
      self.balance = 0.00
      length = 8
      self.account_number = SecureRandom.random_number(10000000000)
      self.routine_number = SecureRandom.random_number(1000000000)
      self.status = "false"
    end
  end
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :bannerimg, BannerimgUploader

end

app/models/bill.rb
class Bill < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :user


end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :blogimg, BlogimgUploader


end

app/models/board.rb
class Board < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :boardimg, BoardimgUploader

end

app/models/card.rb
class Card < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :user
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user
end

app/models/faq.rb
class Faq < ApplicationRecord

end

app/models/feature.rb
class Feature < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :fimg, FimgUploader

end

app/models/header.rb
class Header < ApplicationRecord
  mount_uploader :headerimg, HeaderimgUploader
  mount_uploader :abtsectionimg, AbtsectionimgUploader
  mount_uploader :featheaderimg, FeatheaderimgUploader
  mount_uploader :plansimg, PlansimgUploader

end

app/models/loan.rb
class Loan < ApplicationRecord

  extend FriendlyId
  friendly_id :business_name, use: :slugged

  belongs_to :user


  mount_uploader :bfs, BfsUploader
  mount_uploader :btr, BtrUploader
  mount_uploader :cr, CrUploader
  mount_uploader :bp, BpUploader
  mount_uploader :pfs, PfsUploader
  mount_uploader :ld, LdUploader




end

app/models/otp.rb
class Otp < ApplicationRecord
  belongs_to :transfer
end

app/models/package.rb
class Package < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :pkimg, PkimgUploader
end

app/models/plan.rb
class Plan < ApplicationRecord
  mount_uploader :planimg, PlanimgUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :serviceimg, ServiceimgUploader

end

app/models/team.rb
class Team < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable, :timeoutable

has_many :accounts, dependent: :destroy
has_many :transfers, dependent: :destroy
has_many :transactions, dependent: :destroy
has_many :bills, dependent: :destroy
has_many :cards, dependent: :destroy
has_many :deposits, dependent: :destroy

has_many :loans, dependent: :destroy


before_validation :load_defaults
def load_defaults
  if self.new_record?
    self.verified = true
    self.status = false

  end
end

end

app/views/shared/_agent.html.erb
<!-- Start Find Agent Area -->
<section class="find-agent-area ptb-100">
    <div class="container">
        <div class="section-title">
            <h2>Find An Insurance Agent</h2>
        </div>

        <div class="row align-items-center">
            <div class="col-lg-6 col-md-12">
                <div class="find-agent-content">
                    <div class="row">
                        <div class="col-lg-12 col-md-6 col-sm-6">
                            <div class="box">
                                <div class="icon">
                                    <i class="flaticon-home-insurance"></i>
                                </div>

                                <h3>Find Insurance from the Best</h3>
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-6 col-sm-6">
                            <div class="box">
                                <div class="icon">
                                    <i class="flaticon-briefcase"></i>
                                </div>

                                <h3>Choose what suits you</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <% if Welcome.exists? %>
            <% @welcomes.take(1).each do |w|%>
            <div class="col-lg-6 col-md-12">
                <div class="find-agent-contact-info">
                    <ul>
                        <li>
                            <div class="icon">
                                <i class="flaticon-call"></i>
                            </div>

                            <span>Talk to our Agent</span>
                            <a href="#"><%= w.phone %></a>
                        </li>

                        <li>
                            <cite>Or</cite>
                        </li>

                        <li>
                            <div class="icon">
                                <i class="flaticon-email"></i>
                            </div>

                            <span>Drop us an Email</span>
                            <a href="mailto:<%= w.footer%>?subject=feedback"><%= w.footer %></a>
                          </li>
                    </ul>
                </div>
            </div>

            <% end %>
            <% else %>
            <div class="col-lg-6 col-md-12">
                <div class="find-agent-contact-info">
                    <ul>
                        <li>
                            <div class="icon">
                                <i class="flaticon-call"></i>
                            </div>

                            <span>Talk to our Agent</span>
                            <a href="#">+1 518 285679</a>
                        </li>

                        <li>
                            <cite>Or</cite>
                        </li>

                        <li>
                            <div class="icon">
                                <i class="flaticon-email"></i>
                            </div>

                            <span>Drop us an Email</span>
                            <a href="#">support@pearo.com</a>
                        </li>
                    </ul>
                </div>
            </div>

            <% end %>


        </div>
    </div>
</section>
<!-- End Find Agent Area -->

app/views/shared/_body.html.erb
<%= render "shared/banner" %>
<div class="site-main">

<%= render "shared/abouts2" %>
<%= render "shared/abtcta" %>
<%= render "shared/plans2" %>

<%= render "shared/services" %>

<%= render "shared/features" %>
<%= render "shared/reviews" %>
<%= render "shared/loanbody" %>
<%= render "shared/board" %>

</div>

app/views/shared/_ctr.html.erb
<!-- Start CTR Area -->
<% if Section.exists? %>
<% @sections.take(1).each do |s| %>
<section class="ctr-area">
    <div class="container">
        <div class="ctr-content">
            <h2><%= s.title %></h2>
            <p><%= s.body %></p>
            <%= link_to s, class: "default-btn"  do %>
        Get a Quote <i class="flaticon-right-chevron"></i><span></span><% end %>
        </div>

        <div class="ctr-image">
            <img src="<%= asset_path "ctr-img.jpg"%>" alt="image">
        </div>

        <div class="shape">
            <img src="<%= asset_path "bg-dot3.png" %>" alt="image">
        </div>
    </div>
</section>
<%end %>
<% else %>
<section class="ctr-area">
    <div class="container">
        <div class="ctr-content">
            <h2>Insurances for your child's future</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
            <a href="#" class="default-btn">Get a Quote <i class="flaticon-right-chevron"></i><span></span></a>
        </div>

        <div class="ctr-image">
            <img src="<%= asset_path "ctr-img.jpg"%>" alt="image">
        </div>

        <div class="shape">
            <img src="<%= asset_path "bg-dot3.png" %>" alt="image">
        </div>
    </div>
</section>
<!-- End CTR Area -->
<% end %>

app/views/shared/_genwidget.html.erb
<% @abouts = About.all.order('created_at DESC') %>
<% @services = Service.all.order('created_at DESC') %>
<% @welcomes = Welcome.all %>
<% @headers = Header.all %>
<% @plans = Plan.all %>
<% @packages = Package.all.order('created_at ASC') %>


  <div class="col-lg-3 widget-area">
      <aside class="widget widget-search">
          <form role="search" method="get" class="search-form  box-shadow" action="#">
              <div class="form-group">
                  <input name="search" type="text" class="form-control bg-white" placeholder="Search....">
                  <i class="fa fa-search"></i>
              </div>
          </form>
      </aside>
      <aside class="widget widget-categories">
          <h3 class="widget-title">Services</h3>
          <ul>
            <% @services.each do |a| %>
              <li><%= link_to a.title, a %></li>
              <% end %>

          </ul>
      </aside>

      <aside class="widget tagcloud-widget">
          <h3 class="widget-title">Banking Solutions</h3>
          <div class="tagcloud">
            <% @plans.each do |a| %>
            <%= link_to a.title, a, class: "tag-cloud-link" %>
              <a href="#" class="tag-cloud-link">Business</a>
              <% end %>

          </div>
      </aside>
      <aside class="widget widget-categories">
          <h3 class="widget-title">Enterprize Loan's</h3>
          <ul>
            <% @packages.take(4).each do |a| %>
              <li><%= link_to a.title, a %></li>
              <% end %>
              <li><%= link_to "View More", packages_path %></li>

          </ul>
      </aside>
      <aside class="widget widget-categories">
          <h3 class="widget-title">Help Center </h3>
          <ul>
            <% @abouts.each do |a| %>
              <%= link_to a.title, a %>
            <% end %>
              <li> <%= link_to "FAQ's", faqs_path %></li>
              <li><%= link_to "News & Update", blogs_path %></li>

          </ul>
      </aside>
  </div>

app/views/shared/_header.html.erb
<% if Welcome.exists? %>
<!--header start-->
<header id="masthead" class="header ttm-header-style-01">
  <!-- ttm-topbar-wrapper -->
  <% @welcomes.take(1).each do |w| %>

  <div class="ttm-topbar-wrapper clearfix">
    <div class="container">
      <div class="ttm-topbar-content">
        <ul class="top-contact text-left">
          <li><i class="fa fa-map-marker"></i><%= w.address %></li>
          <li><i class="fa fa-envelope-o"></i><a href="mailto:<%= w.footer %>"><%= w.footer %></a></li>
          <li>  <div id="google_translate_element"></div></li>

          </ul>
          <div class="topbar-right text-right">
            <div class="header-btn">
              <%= link_to new_user_registration_path, class:"ttm-btn ttm-btn-size-md  ttm-btn-bgcolor-skincolor" do %>
            Online Banking <% end %>
            </div>
          </div>
        </div>
      </div>
    </div><!-- ttm-topbar-wrapper end -->
    <% end %>
    <!-- ttm-header-wrap -->
    <div class="ttm-header-wrap">
      <!-- ttm-stickable-header-w -->
      <div id="ttm-stickable-header-w" class="ttm-stickable-header-w clearfix">
        <div id="site-header-menu" class="site-header-menu">
          <div class="site-header-menu-inner ttm-stickable-header">
            <div class="container">
              <!-- site-branding -->
              <% @welcomes.take(1).each do |w| %>

              <div class="site-branding">
                <%= link_to root_path, class: "home-link" do %>
                <img src="<%= w.logoimg_url.to_s %>", class="img-center" id="logo-img" style="max-height:68px !important;" alt="">
                <% end %>


              </div><!-- site-branding end -->
              <% end %>
              <!--site-navigation -->
              <div id="site-navigation" class="site-navigation">
                <div class="ttm-rt-contact">
                  <!-- header-icons -->
                  <div class="ttm-header-icons ">

                    <div class="ttm-header-icon ">
                      <%= link_to new_user_registration_path do %><i class="ti ti-message"></i> <% end %>
                    </div>
                  </div><!-- header-icons end -->
                </div>
                <div class="ttm-menu-toggle">
                  <input type="checkbox" id="menu-toggle-form" />
                  <label for="menu-toggle-form" class="ttm-menu-toggle-block">
                    <span class="toggle-block toggle-blocks-1"></span>
                    <span class="toggle-block toggle-blocks-2"></span>
                    <span class="toggle-block toggle-blocks-3"></span>
                  </label>
                </div>
                <nav id="menu" class="menu">
                  <ul class="dropdown">
                    <li class="active">  <%= link_to root_path do %>
                      Home
                      <% end %>

                    </li>

                    <li><a href="#">Banking Services</a>
                      <ul>
                        <% @plans.each do |a| %>
                        <li>
                          <%= link_to a.title, a %>
                        </li>
                        <% end %>
                      </ul>
                    </li>

                    <li><a href="#">Enterprise Loan's</a>

                      <ul>

                        <li><a href="#">Assets & Loans </a>
                            <ul>
                              <% @packages.each do |a| %>
                              <li>
                                <%= link_to a.title, a %>
                              </li>
                              <% end %>
                              <li><%= link_to packages_path do %>Goto Loans Homepage <% end %></li>
                              </ul>
                        </li>

                        <li><a href="#">Our Services</a>
                            <ul>
                              <% @services.each do |a| %>
                              <li>
                                <%= link_to a.title, a %>
                              </li>
                              <% end %>
                            </ul>
                        </li>

                      </ul>

                    </li>

                    <li><a href="#">Help Center</a>
                      <ul>
                        <% @abouts.each do |a| %>
                        <li>
                          <%= link_to a.title, a %>
                        </li>
                        <% end %>
                        <li><%= link_to "News Updates", blogs_path %></li>

                        <li >
                          <%= link_to "FAQ's", faqs_path %>

                        </li>

                        <li >
                          <%= link_to "Management Team", boards_path %>

                        </li>

                      </ul>
                    </li>


                    <li><%= link_to "Online Banking", new_user_registration_path %></li>



                  </ul>
                </nav>
              </div><!-- site-navigation end-->
            </div>
          </div>
        </div>
      </div><!-- ttm-stickable-header-w end-->
    </div><!--ttm-header-wrap end -->

  </header><!--header end-->


  <% else %>

  <!--header start-->
  <header id="masthead" class="header ttm-header-style-01">
    <!-- ttm-topbar-wrapper -->
    <div class="ttm-topbar-wrapper clearfix">
      <div class="container">
        <div class="ttm-topbar-content">
          <ul class="top-contact text-left">
            <li><i class="fa fa-map-marker"></i>24 Tech Roqad st Ny 10023</li>
            <li><i class="fa fa-envelope-o"></i><a href="mailto:info@example.com.com">info@example.com</a></li>
          </ul>
          <div class="topbar-right text-right">
            <ul class="top-contact">
              <li><i class="fa fa-clock-o"></i>Office Hour: 08:00am - 6:00pm</li>
            </ul>
            <div class="ttm-social-links-wrapper list-inline">
              <ul class="social-icons">
                <li><a href="#" class=" tooltip-bottom" data-tooltip="Facebook"><i class="fa fa-facebook"></i></a>
                </li>
                <li><a href="#" class=" tooltip-bottom" data-tooltip="Twitter"><i class="fa fa-twitter"></i></a>
                </li>
                <li><a href="#" class=" tooltip-bottom" data-tooltip="Flickr"><i class="fa fa-flickr"></i></a>
                </li>
                <li><a href="#" class=" tooltip-bottom" data-tooltip="Linkedin"><i class="fa fa-linkedin"></i></a>
                </li>
              </ul>
            </div>
            <div class="header-btn">
              <a class="ttm-btn ttm-btn-size-md  ttm-btn-bgcolor-skincolor" href="#">Get A Quote</a>
            </div>
          </div>
        </div>
      </div>
    </div><!-- ttm-topbar-wrapper end -->
    <!-- ttm-header-wrap -->
    <div class="ttm-header-wrap">
      <!-- ttm-stickable-header-w -->
      <div id="ttm-stickable-header-w" class="ttm-stickable-header-w clearfix">
        <div id="site-header-menu" class="site-header-menu">
          <div class="site-header-menu-inner ttm-stickable-header">
            <div class="container">
              <!-- site-branding -->
              <div class="site-branding">
                <a class="home-link" href="index.html" title="Altech" rel="home">
                  <img id="logo-img" class="img-center" src=" <%= asset_path "logo.png" %>" alt="logo">
                </a>
              </div><!-- site-branding end -->
              <!--site-navigation -->
              <div id="site-navigation" class="site-navigation">
                <div class="ttm-rt-contact">
                  <!-- header-icons -->
                  <div class="ttm-header-icons ">
                    <span class="ttm-header-icon ttm-header-cart-link">
                      <a href="#"><i class="ti ti-shopping-cart"></i>
                        <span class="number-cart">0</span>
                      </a>
                    </span>
                    <div class="ttm-header-icon ttm-header-search-link">
                      <a href="#"><i class="ti ti-search"></i></a>
                      <div class="ttm-search-overlay">
                        <form method="get" class="ttm-site-searchform" action="#">
                          <div class="w-search-form-h">
                            <div class="w-search-form-row">
                              <div class="w-search-input">
                                <input type="search" class="field searchform-s" name="s" placeholder="Type Word Then Enter...">
                                <button type="submit">
                                  <i class="ti ti-search"></i>
                                </button>
                              </div>
                            </div>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div><!-- header-icons end -->
                </div>
                <div class="ttm-menu-toggle">
                  <input type="checkbox" id="menu-toggle-form" />
                  <label for="menu-toggle-form" class="ttm-menu-toggle-block">
                    <span class="toggle-block toggle-blocks-1"></span>
                    <span class="toggle-block toggle-blocks-2"></span>
                    <span class="toggle-block toggle-blocks-3"></span>
                  </label>
                </div>
                <nav id="menu" class="menu">
                  <ul class="dropdown">
                    <li class="active"><a href="#">Home</a>
                      <ul>
                        <li><a href="index.html">Homepage 1</a></li>
                        <li class="active"><a href="home-2.html">Homepage 2</a></li>
                        <li><a href="home-3.html">Homepage 3</a></li>
                        <li><a href="#">Header Styles</a>
                          <ul>
                            <li><a href="index.html">Header Style 01</a></li>
                            <li><a target="_blank" href="header-style-02.html">Header Style 02</a></li>
                            <li><a target="_blank" href="header-style-03.html">Header Style 03</a></li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                    <li><a href="#">Pages</a>
                      <ul>
                        <li><a href="aboutus-01.html">About Us 1</a></li>
                        <li><a href="aboutus-02.html">About Us 2</a></li>
                        <li><a href="services-01.html">Services 1</a></li>
                        <li><a href="services-02.html">Services 2</a></li>
                        <li><a href="our-expert.html">Our Expert</a></li>
                        <li><a href="faq.html">FAQs</a></li>
                        <li><a href="contact-01.html">Contact Us 1</a></li>
                        <li><a href="contact-02.html">Contact Us 2</a></li>

                        <li><a href="error.html">Error Page</a></li>
                        <li><a href="element.html">Elements</a></li>
                      </ul>
                    </li>
                    <li><a href="#">Services</a>
                      <ul>
                        <li><a href="it-consultancy.html">IT Consultancy</a></li>
                        <li><a href="digital-services.html">Digital Services</a></li>
                        <li><a href="advisory-services.html">Advisory Services</a></li>
                        <li><a href="data-structuring.html">Data Structuring</a></li>
                        <li><a href="experience-design.html">Experience Design</a></li>
                        <li><a href="content-engineering.html">Content Engineering</a></li>
                      </ul>
                    </li>
                    <li><a href="#">Project</a>
                      <ul>
                        <li><a href="project-style-01.html">Project Style 1</a></li>
                        <li><a href="project-style-02.html">Project Style 2</a></li>
                        <li><a href="#">Project Single</a>
                          <ul>
                            <li><a href="single-style-01.html">Single Style 1</a></li>
                            <li><a href="single-style-02.html">Single Style 2</a></li>
                            <li><a href="single-style-03.html">Single Style 3</a></li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                    <li><a href="#">Blog</a>
                      <ul>
                        <li><a href="blog.html">Blog Classic</a></li>
                        <li><a href="blog-grid.html">Blog Grid View</a></li>
                        <li><a href="blog-top-image.html">Blog Top Image</a></li>
                        <li><a href="blog-left-image.html">Blog Left Image</a></li>
                        <li><a href="single-blog.html">Blog Single View</a></li>
                      </ul>
                    </li>
                    <li><a href="#">Shop</a>
                      <ul>
                        <li><a href="shop.html">Default Shop</a></li>
                        <li><a href="product-details.html">Single Product Details</a></li>
                        <li><a href="cart.html">Cart</a></li>
                        <li><a href="checkout.html">Checkout</a></li>
                      </ul>
                    </li>
                  </ul>
                </nav>
              </div><!-- site-navigation end-->
            </div>
          </div>
        </div>
      </div><!-- ttm-stickable-header-w end-->
    </div><!--ttm-header-wrap end -->

  </header><!--header end-->


  <% end %>

app/views/shared/_loancta.html.erb
            <!-- cta-section -->

            <section class="ttm-row cta-section vector_bg-img2 clearfix" style="background-image:url(<%=asset_path "vector_page/vector-row-bg-2.jpg" %>)" >
                <div class="container">
                    <div class="row align-items-md-center justify-content-between"><!-- row -->
                        <div class="col-lg-7 col-md-7 mr-auto">
                            <!-- section-title -->
                            <div class="section-title clearfix">
                                <div class="title-header">
                                    <h5>More Than 50,000 Happy Client</h5>
                                    <h2 class="title">We Provide The Best Loan  Services For Small & <span>Mid-Sized Business</span></h2>
                                </div>
                                <div class="title-desc">NavyXSeal Federal Credit Union offers tailored loans with competitive rates and flexible terms. From term loans to SBA and equipment financing, we have the solution for your business needs. Apply now and secure the financial support your business deserves!</div>
                            </div><!-- section-title end -->


                            <div class="mt-40 res-991-mb-30">

                              <%= link_to new_loan_path, class: "ttm-btn ttm-btn-size-md ttm-btn-style-border ttm-btn-color-darkgrey" do %>
                          Apply Now <% end %>
                            </div>

                        </div>
                        <div class="col-lg-1 col-md-2">
                            <div class="ttm-play-icon-btn m-auto d-block text-center">
                                <div class="ttm-play-icon-animation">
                                    <a href="#" target="_self" class="ttm_prettyphoto">
                                        <div class="ttm-icon ttm-icon_element-bgcolor-white ttm-icon_element-size-sm ttm-icon_element-style-round">
                                            <i class="fa fa-play"></i>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- cta-section END-->

app/views/shared/_transfers.html.erb
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
              <%= link_to new_transfer_path, class: "btn btn-primary px-4 float-right mt-0 mb-3" do %>

              <<i class="mdi mdi-plus-circle-outline mr-2"></i>Make A Transfer<% end %>
                <h4
                    class="header-title mt-0">Recent Transactions</h4>
                    <div class="table-responsive dash-social">
                        <table id="datatable" class="table">
                            <thead class="thead-light">
                                <tr>
                                  <th>Date</th>
                                  <th>Record</th>
                                  <th>Method</th>
                                  <th>Amount</th>
                                  <th>Details</th>
                                  <th>Status</th>

                                </tr>
                                <!--end tr-->
                            </thead>
                            <tbody>

                                            <% if Transfer.where(user_id: current_user.id).exists? %>
                                            <% @transfers.each do |t| %>
                                            <tr>
                                              <td><%= t.created_at.to_datetime.strftime('%b %d %Y %I:%M%p') %></td>
                                              <td> Debit</td>
                                              <td> <%= t.transfer_type %></td>
                                              <td> <%= t.amount %> </td>
                                              <td> <%= t.account_name %></td>
                                              <td><% if current_user.status? %>
                                                 <% if t.status? %>
                                                 <%= link_to t, class: "btn btn-success" do %>
                                                  View receipt <% end %>
                                                <% else %>
                                                 <%= link_to t, class: "btn btn-warning" do %>
                                                Transfer processing <% end %>
                                                <% end %>
                                                <% else %>
                                                <%= link_to "#", class: "btn btn-danger" do %> Transfer Cancelled <% end %> <% end %></td>

                                            </tr>
                                            <% end %>
                                            <% else %>
                                            <!--end tr-->
                                            <tr>
                                              <td>.</td>
                                              <td>No Data</td>
                                            </tr>
                                            <% end %>
                            </tbody>
                        </table>
                    </div>
            </div>
            <!--end card-body-->
        </div>
        <!--end card-->
    </div>
    <!--end col-->
</div>