config/routes.rb
Rails.application.routes.draw do
  resources :adminloans
  resources :loans
  resources :packages
  get 'userorder', to: 'loans#userorder'

  resources :deposits
  resources :feedbacks
  resources :features
  resources :boards
  resources :headers
  resources :cards
  resources :bills
  resources :transfers do
    resources :otps
  end
  resources :transactions
  resources :contacts
  resources :accounts
  resources :banners
  resources :blogs
  resources :faqs
  resources :plans
  resources :sections
  resources :services
  resources :abouts
  # mount Ckeditor::Engine => '/ckeditor'
  resources :welcomes
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end
    root "welcomes#index"

      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :abtimg, AbtimgUploader

end

app/models/account.rb
class Account < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :account_number, use: :slugged
  belongs_to :user
  
  validates :balance, presence: true
  before_validation :load_defaults
  has_many :transfers, dependent: :destroy
  accepts_nested_attributes_for :transfers

  def load_defaults
    if self.new_record?
      self.balance = 0.00
      length = 8
      self.account_number = SecureRandom.random_number(10000000000)
      self.routine_number = SecureRandom.random_number(1000000000)
      self.status = "false"
    end
  end
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :bannerimg, BannerimgUploader

end

app/models/bill.rb
class Bill < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :user


end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :blogimg, BlogimgUploader


end

app/models/board.rb
class Board < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :boardimg, BoardimgUploader

end

app/models/card.rb
class Card < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :user
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user
end

app/models/faq.rb
class Faq < ApplicationRecord

end

app/models/feature.rb
class Feature < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :fimg, FimgUploader

end

app/models/header.rb
class Header < ApplicationRecord
  mount_uploader :headerimg, HeaderimgUploader
  mount_uploader :abtsectionimg, AbtsectionimgUploader
  mount_uploader :featheaderimg, FeatheaderimgUploader
  mount_uploader :plansimg, PlansimgUploader

end

app/models/loan.rb
class Loan < ApplicationRecord

  extend FriendlyId
  friendly_id :business_name, use: :slugged

  belongs_to :user


  mount_uploader :bfs, BfsUploader
  mount_uploader :btr, BtrUploader
  mount_uploader :cr, CrUploader
  mount_uploader :bp, BpUploader
  mount_uploader :pfs, PfsUploader
  mount_uploader :ld, LdUploader




end

app/models/otp.rb
class Otp < ApplicationRecord
  belongs_to :transfer
end

app/models/package.rb
class Package < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :pkimg, PkimgUploader
end

app/models/plan.rb
class Plan < ApplicationRecord
  mount_uploader :planimg, PlanimgUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :serviceimg, ServiceimgUploader

end

app/models/team.rb
class Team < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable, :timeoutable

has_many :accounts, dependent: :destroy
has_many :transfers, dependent: :destroy
has_many :transactions, dependent: :destroy
has_many :bills, dependent: :destroy
has_many :cards, dependent: :destroy
has_many :deposits, dependent: :destroy

has_many :loans, dependent: :destroy


before_validation :load_defaults
def load_defaults
  if self.new_record?
    self.verified = true
    self.status = false

  end
end

end

app/models/welcome.rb
class Welcome < ApplicationRecord
  mount_uploader :logoimg, LogoimgUploader

end

app/controllers/bills_controller.rb
class BillsController < InheritedResources::Base
  layout "accounts"
    before_action :authenticate_user!
    before_action :find_bill, only: [ :show, :edit, :update, :destroy]

      def index
        @users = User.where(user_id: current_user)
        @bills = Bill.where(user_id: current_user).order('created_at DESC')
        @accounts = Account.where(user_id: current_user).order('created_at ASC')
        @transactions = Transaction.where(user_id: current_user).order('created_at DESC')
        @transfers = Transfer.where(user_id: current_user).order('created_at DESC')

      end

      def show

      end

      def new
        @bill = current_user.bills.build

      end

      def create
        @bill = current_user.bills.build(bill_params)
        if @bill.save
          user = User.find_by_id(@bill.user_id)
          bill = @bill
          redirect_to root_path, notice: " New Bill Recorded"
        else
          render 'new'
        end
      end
      def edit

      end

      def update
        if @bill.update(bill_params)
          redirect_to @bill
        else
          render 'edit'
        end
      end

      private
      def find_bill
        @bill = Bill.friendly.find(params[:id])

      end
    def bill_params
      params.require(:bill).permit(:name, :service, :amount, :date, :user_id, :slug)
    end

end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= simple_form_for(@bill) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :service %>
    <%= f.input :amount %>
    <%= f.input :date, as: :datetime %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<div class="container-fluid">

    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
          <div class="card text-white card-dark">
              <div class="card-body">
                  <blockquote class="card-bodyquote mb-0">
                      <p> You can make paying bills easier and well accounted for </p>
                      <footer class="blockquote-footer text-white font-14">
                        Hello  <%= current_user.first_name %>
                      </footer>
                  </blockquote>
              </div><!--end card-body-->
          </div><!--end card-->
          <br>
            <div class="page-title-box">
                <div class="float-right">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0);">Account</a></li>
                        <li class="breadcrumb-item"><a href="javascript:void(0);">Bills</a></li>
                    </ol>
                </div>
                <h4 class="page-title">Account</h4>
            </div>
            <!--end page-title-box-->
        </div>
        <!--end col-->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title mt-0">Bills Records</h4>
                    <div class="">
                        <div id="ana_dash_1" class="apex-charts"></div>
                    </div>
                </div>
                <!--end card-body-->
            </div>
            <!--end card-->

    </div>
    </div>
    <div class="row justify-content-center">
      <% if Bill.where(user_id: current_user.id).exists? %>

    <% @bills.each do |a| %>


    <!--end row-->
        <div class="col-lg-4">
            <div class="card report-card">
                <div class="card-body">
                  <div class="float-right"><i class="dripicons-user-group report-main-icon"></i></div>
                  <span class="badge badge-success">Bills </span>
                        <div class="row">
                            <div class="col-8 align-self-center">
                                <h5 class="">Bills Records</h5>

                            </div>
                            <!--end col-->
                            <div class="col-4">  <h4><%= Bill.where(user_id: current_user.id).count %>
.</h4></div>
                            <!--end col-->
                        </div>
                        <!--end row-->
                    <!--end icon-contain-->
                </div>
                <!--end card-body-->
            </div>
            <!--end card-->
        </div>
        <!--end col-->
        <% end %>
        <% else %>
        <div class="col-lg-4">
            <div class="card report-card">
                <div class="card-body">
                  <div class="float-right"><i class="dripicons-user-group report-main-icon"></i></div>
                  <span class="badge badge-success">Bills</span>
                        <div class="row">
                            <div class="col-6 align-self-center">
                                <h5 class="">Bills History </h5>

                            </div>
                            <!--end col-->
                            <div class="col-6">  <h4>  no data
.</h4></div>
                            <!--end col-->
                        </div>
                        <!--end row-->
                    <!--end icon-contain-->
                </div>
                <!--end card-body-->
            </div>
            <!--end card-->
        </div>
        <!--end col-->
        <% end %>
        <% @accounts.take(1).each do |a| %>

        <div class="col-lg-4">
            <div class="card report-card">
                <div class="card-body">
                    <div class="float-right"><i class="dripicons-meter report-main-icon"></i></div>
                    <span class="badge badge-warning">Overview</span>
                        <div class="row">
                            <div class="col-12 align-self-center">
                                <h5 class="">Account Number: <%= a.account_number %></h5>
                                <p class="text-muted mb-0">Routine Number: <%= a.routine_number %>
                                  <i class="mdi mdi-menu-up text-success font-16"></i></p>
                            </div>
                            <!--end col-->

                            <!--end col-->
                        </div>
                        <!--end row-->
                    <!--end icon-contain-->
                </div>
                <!--end card-body-->
            </div>
            <!--end card-->
        </div>
        <div class="col-lg-4">
            <div class="card report-card">
                <div class="card-body">
                  <div class="float-right">
                    <i class="dripicons-wallet report-main-icon"></i>
                  </div><span class="badge badge-success">Balance</span>

                        <div class="row">
                            <div class="col-6 align-self-center">
                                <h5 class="">Balance</h5>
                                <p class="text-muted mb-0">Book Balance: $<%=a.lbalance %>
                                  <i class="mdi mdi-menu-up text-success font-16"></i></p>
                            </div>
                            <!--end col-->
                            <div class="col-6">
                          <h4>    $ <%= a.balance %></h4>
                            </div>
                            <!--end col-->
                        </div>
                        <!--end row-->
                    <!--end icon-contain-->
                </div>
                <!--end card-body-->
            </div>
            <!--end card-->
        </div>


        </div>
        <!--end col-->
    </div>
    <!--end row-->
    <% end %>
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <%= link_to new_bill_path, class: "btn btn-primary px-4 float-right mt-0 mb-3" do %>

            <<i class="mdi mdi-plus-circle-outline mr-2"></i>Record Bill Payments <% end %>
            <h4
            class="header-title mt-0">Recent Transactions</h4>
            <div class="table-responsive dash-social">
              <table id="datatable" class="table">
                <thead class="thead-light">
                  <tr>
                    <th>Name</th>
                    <th>Service</th>
                    <th>Amount</th>
                    <th> Due Date</th>
                    <th>Status</th>

                  </tr>
                  <!--end tr-->
                </thead>
                <tbody>
                  <% if Bill.where(user_id: current_user.id).exists? %>
                  <% @bills.each do |t| %>
                  <tr>
                    <td><%= t.name %></td>
                    <td><%= t.service %></td>
                    <td><%= t.amount %></td>
                    <td><%= t.date.to_datetime.strftime('%b %d %Y %I:%M%p')  %></td>
                    <td><% if t.status? %> <%= link_to "#", class: "btn btn-success" do %> Payment Succesfull <% end %><% else %><%= link_to "#", class: "btn btn-danger" do %> Pending <% end %> <% end %></td>

                  </tr>
                  <% end %>
                  <% else %>
                  <!--end tr-->
                  <tr>
                    <td>.</td>
                    <td>No Data</td>
                  </tr>
                  <% end %>

                </tbody>
              </table>
            </div>
          </div>
          <!--end card-body-->
        </div>
        <!--end card-->
      </div>
      <!--end col-->
    </div>

</div>

app/views/bills/new.html.erb
<!-- Loog In page -->
<div class="row justify-content-center">
    <div class="col-10">
        <div class="auth-page">
            <div class="card auth-card shadow-lg">
                <div class="card-body">


                        <!--end auth-logo-box-->
                        <div class="text-center auth-logo-text">
                            <h4 class="mt-0 mb-3 mt-5">Hello</h4>
                            <p class="text-muted mb-0">Register a bill payment</p>
                        </div>
                        <!--end auth-logo-text-->
                        <div class="col-12">


                          <%= render 'form', bill: @bill %>
</div></div></div></div></div></div>  