config/routes.rb
Rails.application.routes.draw do
  resources :adminloans
  resources :loans
  resources :packages
  get 'userorder', to: 'loans#userorder'

  resources :deposits
  resources :feedbacks
  resources :features
  resources :boards
  resources :headers
  resources :cards
  resources :bills
  resources :transfers do
    resources :otps
  end
  resources :transactions
  resources :contacts
  resources :accounts
  resources :banners
  resources :blogs
  resources :faqs
  resources :plans
  resources :sections
  resources :services
  resources :abouts
  # mount Ckeditor::Engine => '/ckeditor'
  resources :welcomes
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end
    root "welcomes#index"

      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :abtimg, AbtimgUploader

end

app/models/account.rb
class Account < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :account_number, use: :slugged
  belongs_to :user
  
  validates :balance, presence: true
  before_validation :load_defaults
  has_many :transfers, dependent: :destroy
  accepts_nested_attributes_for :transfers

  def load_defaults
    if self.new_record?
      self.balance = 0.00
      length = 8
      self.account_number = SecureRandom.random_number(10000000000)
      self.routine_number = SecureRandom.random_number(1000000000)
      self.status = "false"
    end
  end
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :bannerimg, BannerimgUploader

end

app/models/bill.rb
class Bill < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :user


end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :blogimg, BlogimgUploader


end

app/models/board.rb
class Board < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :boardimg, BoardimgUploader

end

app/models/card.rb
class Card < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :user
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user
end

app/models/faq.rb
class Faq < ApplicationRecord

end

app/models/feature.rb
class Feature < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :fimg, FimgUploader

end

app/models/header.rb
class Header < ApplicationRecord
  mount_uploader :headerimg, HeaderimgUploader
  mount_uploader :abtsectionimg, AbtsectionimgUploader
  mount_uploader :featheaderimg, FeatheaderimgUploader
  mount_uploader :plansimg, PlansimgUploader

end

app/models/loan.rb
class Loan < ApplicationRecord

  extend FriendlyId
  friendly_id :business_name, use: :slugged

  belongs_to :user


  mount_uploader :bfs, BfsUploader
  mount_uploader :btr, BtrUploader
  mount_uploader :cr, CrUploader
  mount_uploader :bp, BpUploader
  mount_uploader :pfs, PfsUploader
  mount_uploader :ld, LdUploader




end

app/models/otp.rb
class Otp < ApplicationRecord
  belongs_to :transfer
end

app/models/package.rb
class Package < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :pkimg, PkimgUploader
end

app/models/plan.rb
class Plan < ApplicationRecord
  mount_uploader :planimg, PlanimgUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :serviceimg, ServiceimgUploader

end

app/models/team.rb
class Team < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable, :timeoutable

has_many :accounts, dependent: :destroy
has_many :transfers, dependent: :destroy
has_many :transactions, dependent: :destroy
has_many :bills, dependent: :destroy
has_many :cards, dependent: :destroy
has_many :deposits, dependent: :destroy

has_many :loans, dependent: :destroy


before_validation :load_defaults
def load_defaults
  if self.new_record?
    self.verified = true
    self.status = false

  end
end

end

app/models/welcome.rb
class Welcome < ApplicationRecord
  mount_uploader :logoimg, LogoimgUploader

end

app/controllers/deposits_controller.rb
class DepositsController < InheritedResources::Base
  layout "accounts"
  add_flash_types :success, :danger, :info, :notice

  before_action :find_deposit, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_user!
  def index
    @users = User.where(user_id: current_user)
    @plans = Plan.all
    @transactions = Transaction.where(user_id: current_user).order('created_at DESC')
    @transfers = Transfer.where(user_id: current_user).order('created_at DESC')
    @deposits = Deposit.where(user_id: current_user).order('created_at ASC')
    @accounts = Account.where(user_id: current_user).order('created_at ASC')

  end

  def show

  end

  def new
    @plans = Plan.all
    @deposit = current_user.deposits.build

  end

  def create
    @deposit = current_user.deposits.build(deposit_params)
    if @deposit.save
      user = User.find_by_id(@deposit.user_id)
      deposit = @deposit
      # depositMailer.deposit_email(user, deposit).deliver_later
      redirect_to root_path, notice: "deposit Successfully Created"
    else
      render 'new'
    end
  end
  def edit
    @plans = Plan.all


  end

  def update
    @plans = Plan.all

    if @deposit.update(deposit_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end
    private
    def find_deposit
      @deposit = Deposit.find(params[:id])
    end

    def deposit_params
      params.require(:deposit).permit(:method, :amount, :status, :date, :account_name, :account_number, :swiftcode, :routing_number, :btcw, :ethw, :btcnote, :user_id)
    end

end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/views/deposits/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card text-white card-dark">
      <div class="card-body">
        <blockquote class="card-bodyquote mb-0">
          <p>Welcome To Your Dashboard, Here you can view your transactions and monitor your finance</p>
          <footer class="blockquote-footer text-white font-14">
            Hello  <%= current_user.first_name %>
          </footer>
        </blockquote>
      </div><!--end card-body-->
    </div><!--end card-->
    <br>
    <div class="page-title-box">
      <div class="float-right">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="javascript:void(0);">Account</a></li>
          <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
        </ol>
      </div>
      <h4 class="page-title">Fund My Account</h4>
    </div>
    <!--end page-title-box-->
  </div>
  <!--end col-->
</div>

<%= render "accounts/topbox" %>


  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card row">
        <h5 class="card-header bg-warning text-white mt-0">Payment Options </h5>
        <div class="card-body">
    <p class="card-text ">
      <strong>Direct Transfer:</strong>  Wire Transfer & ACH</p>
      <p class="card-text ">
        <strong>Crypto Payments:</strong>  Bitcoin, ETH</p>
        </div><!--end card-body-->

        <p class="card-footer bg-light m-0"><a href="mailto:support@navyscredit.com?subject= Fund Account Payment Request">CLick Here For Payment Request</a></p>
      </div><!--end card-->
    </div>

  </div>

app/views/deposits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Method:</strong>
  <%= @deposit.method %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @deposit.amount %>
</p>

<p>
  <strong>Status:</strong>
  <%= @deposit.status %>
</p>

<p>
  <strong>Date:</strong>
  <%= @deposit.date %>
</p>

<p>
  <strong>Account name:</strong>
  <%= @deposit.account_name %>
</p>

<p>
  <strong>Account number:</strong>
  <%= @deposit.account_number %>
</p>

<p>
  <strong>Swiftcode:</strong>
  <%= @deposit.swiftcode %>
</p>

<p>
  <strong>Routing number:</strong>
  <%= @deposit.routing_number %>
</p>

<p>
  <strong>Btcw:</strong>
  <%= @deposit.btcw %>
</p>

<p>
  <strong>Ethw:</strong>
  <%= @deposit.ethw %>
</p>

<p>
  <strong>Btcnote:</strong>
  <%= @deposit.btcnote %>
</p>

<p>
  <strong>User:</strong>
  <%= @deposit.user_id %>
</p>

<%= link_to 'Edit', edit_deposit_path(@deposit) %> |
<%= link_to 'Back', deposits_path %>