config/routes.rb
Rails.application.routes.draw do
  resources :adminloans
  resources :loans
  resources :packages
  get 'userorder', to: 'loans#userorder'

  resources :deposits
  resources :feedbacks
  resources :features
  resources :boards
  resources :headers
  resources :cards
  resources :bills
  resources :transfers do
    resources :otps
  end
  resources :transactions
  resources :contacts
  resources :accounts
  resources :banners
  resources :blogs
  resources :faqs
  resources :plans
  resources :sections
  resources :services
  resources :abouts
  # mount Ckeditor::Engine => '/ckeditor'
  resources :welcomes
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end
    root "welcomes#index"

      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :abtimg, AbtimgUploader

end

app/models/account.rb
class Account < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :account_number, use: :slugged
  belongs_to :user
  
  validates :balance, presence: true
  before_validation :load_defaults
  has_many :transfers, dependent: :destroy
  accepts_nested_attributes_for :transfers

  def load_defaults
    if self.new_record?
      self.balance = 0.00
      length = 8
      self.account_number = SecureRandom.random_number(10000000000)
      self.routine_number = SecureRandom.random_number(1000000000)
      self.status = "false"
    end
  end
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :bannerimg, BannerimgUploader

end

app/models/bill.rb
class Bill < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :user


end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :blogimg, BlogimgUploader


end

app/models/board.rb
class Board < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :boardimg, BoardimgUploader

end

app/models/card.rb
class Card < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :user
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user
end

app/models/faq.rb
class Faq < ApplicationRecord

end

app/models/feature.rb
class Feature < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :fimg, FimgUploader

end

app/models/header.rb
class Header < ApplicationRecord
  mount_uploader :headerimg, HeaderimgUploader
  mount_uploader :abtsectionimg, AbtsectionimgUploader
  mount_uploader :featheaderimg, FeatheaderimgUploader
  mount_uploader :plansimg, PlansimgUploader

end

app/models/loan.rb
class Loan < ApplicationRecord

  extend FriendlyId
  friendly_id :business_name, use: :slugged

  belongs_to :user


  mount_uploader :bfs, BfsUploader
  mount_uploader :btr, BtrUploader
  mount_uploader :cr, CrUploader
  mount_uploader :bp, BpUploader
  mount_uploader :pfs, PfsUploader
  mount_uploader :ld, LdUploader




end

app/models/otp.rb
class Otp < ApplicationRecord
  belongs_to :transfer
end

app/models/package.rb
class Package < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :pkimg, PkimgUploader
end

app/models/plan.rb
class Plan < ApplicationRecord
  mount_uploader :planimg, PlanimgUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :serviceimg, ServiceimgUploader

end

app/models/team.rb
class Team < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable, :timeoutable

has_many :accounts, dependent: :destroy
has_many :transfers, dependent: :destroy
has_many :transactions, dependent: :destroy
has_many :bills, dependent: :destroy
has_many :cards, dependent: :destroy
has_many :deposits, dependent: :destroy

has_many :loans, dependent: :destroy


before_validation :load_defaults
def load_defaults
  if self.new_record?
    self.verified = true
    self.status = false

  end
end

end

app/controllers/transactions_controller.rb
class TransactionsController < InheritedResources::Base
  layout "accounts"
  before_action :authenticate_user!

  def index
    @transactions = Transaction.where(user_id: current_user).order('created_at DESC')
    @accounts = Account.where(user_id: current_user).order('created_at DESC')
    @transfers = Transfer.where(user_id: current_user).order('created_at DESC')


  end
  private

    def transaction_params
      params.require(:transaction).permit(:amount, :transac_type, :bal_type, :date, :purpose, :sender, :status, :user_id, :slug)
    end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/index.html.erb
<div class="container-fluid">

    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
          <div class="card text-white card-dark">
              <div class="card-body">
                  <blockquote class="card-bodyquote mb-0">
                      <p>Here you can view your transaction history and bank statements </p>
                      <footer class="blockquote-footer text-white font-14">
                        Hello  <%= current_user.first_name %>
                      </footer>
                  </blockquote>
              </div><!--end card-body-->
          </div><!--end card-->
          <br>
            <div class="page-title-box">
                <div class="float-right">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0);">Account</a></li>
                        <li class="breadcrumb-item"><a href="javascript:void(0);">Transactions</a></li>
                    </ol>
                </div>
                <h4 class="page-title">Account</h4>
            </div>
            <!--end page-title-box-->
        </div>
        <!--end col-->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title mt-0">Transactions History</h4>
                    <div class="">
                        <div id="ana_dash_1" class="apex-charts"></div>
                    </div>
                </div>
                <!--end card-body-->
            </div>
            <!--end card-->

    </div>
    </div>


    <div class="row justify-content-center">



  <!--end row-->
        <div class="col-lg-4">
            <div class="card report-card">
                <div class="card-body">
                  <div class="float-right"><i class="dripicons-user-group report-main-icon"></i></div>
                  <span class="badge badge-success">Transactions</span>
                        <div class="row">
                            <div class="col-8 align-self-center">
                                <h5 class="">Account Transactions</h5>

                            </div>
                            <!--end col-->
                            <div class="col-4">  <h4><%= Transaction.where(user_id: current_user.id).count %>
.</h4></div>
                            <!--end col-->
                        </div>
                        <!--end row-->
                    <!--end icon-contain-->
                </div>
                <!--end card-body-->
            </div>
            <!--end card-->
        </div>
        <!--end col-->

        <% @accounts.take(1).each do |a| %>

        <div class="col-lg-4">
            <div class="card report-card">
                <div class="card-body">
                    <div class="float-right"><i class="dripicons-meter report-main-icon"></i></div>
                    <span class="badge badge-warning">Overview</span>
                        <div class="row">
                            <div class="col-12 align-self-center">
                                <h5 class="">Account Number: <%= a.account_number %></h5>
                                <p class="text-muted mb-0">Routing Number: <%= a.routine_number %>
                                  <i class="mdi mdi-menu-up text-success font-16"></i></p>
                            </div>
                            <!--end col-->

                            <!--end col-->
                        </div>
                        <!--end row-->
                    <!--end icon-contain-->
                </div>
                <!--end card-body-->
            </div>
            <!--end card-->
        </div>
        <div class="col-lg-4">
            <div class="card report-card">
                <div class="card-body">
                  <div class="float-right">
                    <i class="dripicons-wallet report-main-icon"></i>
                  </div><span class="badge badge-success">Balance</span>

                        <div class="row">
                            <div class="col-6 align-self-center">
                                <h5 class="">Balance</h5>
                                <p class="text-muted mb-0">Book Balance: $<%=a.lbalance %>
                                  <i class="mdi mdi-menu-up text-success font-16"></i></p>
                            </div>
                            <!--end col-->
                            <div class="col-6">
                          <h4>    $ <%= a.balance %></h4>
                            </div>
                            <!--end col-->
                        </div>
                        <!--end row-->
                    <!--end icon-contain-->
                </div>
                <!--end card-body-->
            </div>
            <!--end card-->
        </div>


        </div>
        <!--end col-->
    </div>
    <!--end row-->
    <% end %>
  <%= render "shared/transactions" %>

</div>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Transac type:</strong>
  <%= @transaction.transac_type %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @transaction.purpose %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @transaction.sender %>
</p>

<p>
  <strong>Status:</strong>
  <%= @transaction.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @transaction.user %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @transaction.slug %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>